trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Test
    jobs:
      - job: TestJob
        steps:

        - task: PowerShell@2
          displayName: Install InvokeBuild module on the build agent
          inputs:
            targetType: 'inline'
            pwsh: true
            script: |
              if (-not (Get-Module -Name InvokeBuild -ListAvailable)) {
                Install-Module InvokeBuild -Force
              }
              Import-Module InvokeBuild

        - task: PowerShell@2
          displayName: Analyze code with PSScriptAnalyzer
          inputs:
            targetType: 'inline'
            pwsh: true
            failOnStderr: false
            script: Invoke-Build -Task Analyze
            workingDirectory: $(System.DefaultWorkingDirectory)

        - task: PublishTestResults@2
          displayName: Publish code analysis results
          condition: succeededOrFailed()
          inputs:
            testResultsFormat: 'NUnit'
            testResultsFiles: '$(System.DefaultWorkingDirectory)/**/AnalysisResults*.xml'
            failTaskOnFailedTests: true

        - task: PowerShell@2
          displayName: Test code with Pester tests
          inputs:
            targetType: 'inline'
            pwsh: true
            failOnStderr: false
            script: Invoke-Build -Task Test
            workingDirectory: $(System.DefaultWorkingDirectory)

        - task: PublishTestResults@2
          displayName: Publish test results
          condition: succeededOrFailed()
          inputs:
            testResultsFormat: 'NUnit'
            testResultsFiles: '$(System.DefaultWorkingDirectory)/**/TestResults*.xml'
            failTaskOnFailedTests: true

        - task: PowerShell@2
          displayName: Verify code coverage
          inputs:
            targetType: 'inline'
            pwsh: true
            failOnStderr: true
            script: Invoke-Build -Task CodeCoverage
            workingDirectory: $(System.DefaultWorkingDirectory)

        - task: PublishCodeCoverageResults@1
          displayName: Publish code coverage results
          condition: succeededOrFailed()
          inputs:
            codeCoverageTool: 'JaCoCo'
            summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/CodeCoverageResults*.xml'
            pathToSources: '$(System.DefaultWorkingDirectory)/$(module.Name)/'
            failIfCoverageEmpty: true

  - stage: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) # Create builds only from the master branch
    jobs:
      - job: BuildJob
        steps:

          - task: PowerShell@2
            displayName: Install InvokeBuild module on the build agent
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                if (-not (Get-Module -Name InvokeBuild -ListAvailable)) {
                  Install-Module InvokeBuild -Force
                }
                Import-Module InvokeBuild

          - task: PowerShell@2
            displayName: Build PowerShell module
            inputs:
              targetType: 'inline'
              pwsh: true
              failOnStderr: false
              script: Invoke-Build -Task Build -Configuration Release -Sourcelocation $(module.SourceLocation)
              workingDirectory: $(System.DefaultWorkingDirectory)

          - task: NuGetCommand@2
            displayName: Create a NuGet package
            inputs:
              command: 'pack'
              packagesToPack: '$(System.DefaultWorkingDirectory)/build/**/*.nuspec'
              packDestination: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: Publish build artifact
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(module.Name)'
              publishLocation: Container

  - stage: Publish
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) # Publish the module only from the master branch
    jobs:
    - job: PublishJob
      steps:

        - task: DownloadPipelineArtifact@2
          displayName: Download pipeline artifact
          inputs:
            buildType: 'current'
            artifactName: '$(module.Name)'
            itemPattern: '**/*.nupkg'
            targetPath: '$(Pipeline.Workspace)'

        - task: NuGetCommand@2
          displayName: Publish module to NuGet feed
          inputs:
            command: 'push'
            packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
            feedsToUse: 'select'
            vstsFeed: 'powershell.sample-module/AMGallery'
            # publishVstsFeed: 'AMGallery'